Update to use Spring Boot 2.x and Camel 3.5.0
Playtika/sleuth-camel pull request #8
Opened 2020-10-12 13:07 UTC by oliverbrandt

- Bumps Camel version to 3.5.0
- Bumps Spring Cloud Release to Hoxton.SR8.
- Fixes incompatibility problems and failing unit tests.

2020-10-13 02:32 UTC, tdanylchuk requested changes

2020-10-13 02:32 UTC, tdanylchuk commented on pom.xml
> +    <version>3.5.0-SNAPSHOT</version>
please dont change project version

2020-10-13 02:32 UTC, tdanylchuk commented on pom.xml
> +        <maven.compiler.source>11</maven.compiler.source>
any reason why need to force 11 java, i would prefer stick to 8 if possible

2020-10-13 02:32 UTC, tdanylchuk commented on sleuth-camel-core/pom.xml
> +            <artifactId>camel-direct-starter</artifactId>
what for this dependency?

2020-10-14 12:22 UTC, oliverbrandt commented on sleuth-camel-core/pom.xml
> +            <artifactId>camel-direct-starter</artifactId>
This is due to the changed Camle packaging since 3.0.
The scope will be changed to test.

2020-10-14 13:52 UTC, tdanylchuk approved these changes

2020-10-14 13:52 UTC, merged

2020-10-14 13:55 UTC, tdanylchuk commented
thank you for your contribution!
release 2.0 should be in maven repo within 24 hours